import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  Logger,
  NotImplementedException,
  UnauthorizedException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from 'octokit';
import { GeneratorService } from '../generator/generator.service';

interface GithubTokenResponse {
  access_token?: string;
  error?: string;
  error_description?: string;
}

interface OctokitError {
  status: number;
  message: string;
}

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);

  constructor(
    private readonly configService: ConfigService,
    private readonly generatorService: GeneratorService,
  ) {}

  // ------------------------------------------------------------------ helpers

  private requireConfig(): { clientId: string; clientSecret: string } {
    const clientId = this.configService.get<string>('GITHUB_CLIENT_ID');
    const clientSecret = this.configService.get<string>('GITHUB_CLIENT_SECRET');
    if (!clientId || !clientSecret) {
      throw new NotImplementedException(
        'GitHub integration is not configured on this server',
      );
    }
    return { clientId, clientSecret };
  }

  private mapOctokitError(err: unknown): never {
    const e = err as OctokitError;
    if (e.status === 401) {
      throw new UnauthorizedException('Invalid or expired GitHub token');
    }
    if (e.status === 403) {
      throw new ForbiddenException(
        'GitHub token lacks required permissions (needs "repo" scope)',
      );
    }
    throw new BadRequestException(
      e.message ?? 'Unexpected error communicating with GitHub',
    );
  }

  // ------------------------------------------------------------------ public API

  /**
   * Exchanges a GitHub OAuth authorization code for an access token.
   * The token is returned to the caller (frontend) and never stored server-side.
   */
  async exchangeCode(
    code: string,
  ): Promise<{ githubToken: string; githubUsername: string }> {
    const { clientId, clientSecret } = this.requireConfig();

    // Exchange code for access token via GitHub OAuth endpoint
    const tokenRes = await fetch(
      'https://github.com/login/oauth/access_token',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify({
          client_id: clientId,
          client_secret: clientSecret,
          code,
        }),
      },
    );

    const tokenData = (await tokenRes.json()) as GithubTokenResponse;

    if (tokenData.error || !tokenData.access_token) {
      this.logger.warn(
        `GitHub OAuth exchange failed: ${tokenData.error_description ?? tokenData.error}`,
      );
      throw new BadRequestException(
        tokenData.error_description ??
          'Invalid or expired GitHub authorization code',
      );
    }

    const githubToken = tokenData.access_token;

    // Fetch the authenticated user's login name
    try {
      const octokit = new Octokit({ auth: githubToken });
      const { data: user } = await octokit.rest.users.getAuthenticated();
      return { githubToken, githubUsername: user.login };
    } catch (err) {
      this.mapOctokitError(err);
    }
  }

  /**
   * Generates the static portfolio and pushes it to <username>.github.io on GitHub.
   * Enables GitHub Pages if not already active. Force-pushes on subsequent deploys.
   */
  async deploy(
    userId: string,
    siteId: string,
    githubToken: string,
  ): Promise<{ repoUrl: string; pagesUrl: string }> {
    this.requireConfig();

    const octokit = new Octokit({ auth: githubToken });

    // Identify the authenticated GitHub user
    let owner: string;
    try {
      const { data: user } = await octokit.rest.users.getAuthenticated();
      owner = user.login;
    } catch (err) {
      this.mapOctokitError(err);
    }

    const repoName = `${owner}.github.io`;
    this.logger.log(`Deploying site ${siteId} to ${owner}/${repoName}`);

    // Generate all static files in memory
    const files = await this.generatorService.generateFiles(userId, siteId);

    // Create the repo (public) or get existing — 422 means it already exists
    try {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        private: false,
        auto_init: true, // creates main branch with initial commit
        description: 'Portfolio generated by webCV',
      });
      this.logger.log(`Created new repo ${owner}/${repoName}`);
    } catch (err) {
      const e = err as OctokitError;
      if (e.status === 422) {
        this.logger.log(`Repo ${owner}/${repoName} already exists — updating`);
      } else {
        this.mapOctokitError(err);
      }
    }

    // Determine the default branch
    let defaultBranch = 'main';
    try {
      const { data: repoInfo } = await octokit.rest.repos.get({
        owner,
        repo: repoName,
      });
      defaultBranch = repoInfo.default_branch || 'main';
    } catch (err) {
      this.mapOctokitError(err);
    }

    // Get the latest commit SHA on the default branch
    let latestSha: string | undefined;
    try {
      const { data: ref } = await octokit.rest.git.getRef({
        owner,
        repo: repoName,
        ref: `heads/${defaultBranch}`,
      });
      latestSha = ref.object.sha;
    } catch (err) {
      const e = err as OctokitError;
      // 404 or 409 can happen if the repo is completely empty (no commits yet)
      if (e.status !== 404 && e.status !== 409) {
        this.mapOctokitError(err);
      }
    }

    // Create blobs for all files
    const treeEntries = await Promise.all(
      files.map(async (file) => {
        const isBinary = file.buffer !== null;
        const content = isBinary
          ? file.buffer!.toString('base64')
          : (file.text ?? '');
        const encoding = isBinary ? 'base64' : 'utf-8';

        const { data: blob } = await octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content,
          encoding,
        });

        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha,
        };
      }),
    );

    // Create tree (without base_tree → clean replace, no leftover files)
    const { data: newTree } = await octokit.rest.git.createTree({
      owner,
      repo: repoName,
      tree: treeEntries,
    });

    // Create commit
    const commitParams: any = {
      owner,
      repo: repoName,
      message: 'Deploy portfolio via webCV',
      tree: newTree.sha,
    };
    if (latestSha) {
      commitParams.parents = [latestSha];
    }
    
    const { data: newCommit } = await octokit.rest.git.createCommit(commitParams);

    try {
      if (latestSha) {
        // Force-push to existing branch
        await octokit.rest.git.updateRef({
          owner,
          repo: repoName,
          ref: `heads/${defaultBranch}`,
          sha: newCommit.sha,
          force: true,
        });
      } else {
        // Repo was completely empty, so we must create the ref
        await octokit.rest.git.createRef({
          owner,
          repo: repoName,
          ref: `refs/heads/${defaultBranch}`,
          sha: newCommit.sha,
        });
      }
    } catch (err) {
      this.mapOctokitError(err);
    }

    // Enable GitHub Pages (silently skip if already enabled)
    try {
      await octokit.rest.repos.createPagesSite({
        owner,
        repo: repoName,
        source: { branch: defaultBranch, path: '/' },
      });
      this.logger.log(`GitHub Pages enabled for ${owner}/${repoName}`);
    } catch (err) {
      const e = err as OctokitError;
      if (e.status === 409) {
        this.logger.log(
          `GitHub Pages already enabled for ${owner}/${repoName}`,
        );
      } else {
        // Pages activation failure is non-fatal — repo and files are already pushed
        this.logger.warn(
          `Could not enable GitHub Pages for ${owner}/${repoName}: ${e.message}`,
        );
      }
    }

    const repoUrl = `https://github.com/${owner}/${repoName}`;
    const pagesUrl = `https://${owner}.github.io`;

    this.logger.log(`Deploy complete: ${pagesUrl}`);
    return { repoUrl, pagesUrl };
  }
}
